package(
    default_visibility = ["//visibility:public"],
)

load("//tools/bzl:plugin.bzl", "PLUGIN_DEPS_NEVERLINK")

java_library(
    name = "utils",
    srcs = glob(["*.java"]),
    deps = PLUGIN_DEPS_NEVERLINK,
)
